### ISSUE TITLE
setup.py install fails, searches for affinegap.c instead of affinegap.pyx

### ISSUE THREAD

**Issue by maxwshen** [datamade/affinegap#3]
Line 15 in setup.py:
    ext_modules=[Extension('affinegap.affinegap', ['affinegap/affinegap.c'])],

There is no affinegap.c file in the affinegap folder.

**Comment by fgregg** [comment]
I forgot a step in the README 

https://github.com/datamade/affinegap/blob/master/README.md#to-get-set-up-for-development

You need to use cython.
